### ISSUE TITLE
Leverage source map from autorest for the reporting to the line number

### ISSUE THREAD

**Issue by vishrutshah** [Azure/openapi-diff#103]
After discussion with @olydis , here are the reference pointer to leverage source map to improve reporting of the tool.

https://github.com/fearthecowboy/autorest.vscode/blob/5b6069860de30858096af2c257be2fa6e4efab72/src/lib/source-map.ts#L76

**Comment by vladbarosan** [comment]
@olydis can you provide some details how we can use this please ? it would be good if we can leverage it.

**Comment by olydis** [comment]
@vladbarosan when asking AutoRest for the Swaggers to compare, you can also ask for a corresponding source map (e.g. if you ask for `output-artifact: swagger-document`, you can also ask for `output-artifact: swagger-document.map`). This map will essentially allow mapping any "object path" like `$.definitions.Resource.location` to it's line+column of the *original* input documents. The link pointed to by Vish contains helper functions showing how to extract that information from the source map using nothing but the `source-map` npm package 🙂
