### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException in Open API Diff

### ISSUE THREAD

**Issue by sarangan12** [Azure/openapi-diff#113]
Ref: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/375027567 

@vladbarosan As discussed offline, Please check if this issue has already been fixed. If so, then we need to ensure that the CI tool picks up the latest ones. Else, this issue must be fixed (and then ensure that the CI tool picks it up)

**Comment by vladbarosan** [comment]
it should be fixed after with 0.1.11 release
