### ISSUE TITLE
Diff Tool Not Catching Change in Format

### ISSUE THREAD

**Issue by sarangan12** [Azure/openapi-diff#135]
https://raw.githubusercontent.com/kalyanaj/azure-rest-api-specs/96910ceb6f894dbd295d3db8a0fe4ee54bd0deaf/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/8c304e7250847a0221171ef82400ce4115d32667/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json

The change in format should be caught. But it is not caught.

**Comment by michaeljqzq** [comment]
Verified resolved.
