### ISSUE TITLE
Supported Swagger/OpenAPI versions

### ISSUE THREAD

**Issue by hcsalis** [Azure/openapi-diff#145]
Hello,

When I run the tool against two OpenAPI v3 spec. files I get the following error and currently there is no mention of supported versions in the readme.

```
FATAL: Error: File 'file:///usr/src/app/petstore-example-api/api.yaml' is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')
```

Is v2 the only version supported by the tool and if so, do you have any plans for supporting v3?

**Comment by michaeljqzq** [comment]
@hcsalis Yes, currently we only support v2

**Comment by adriengibrat** [comment]
1. Is it really a definitve answer ?
2. Could the readme clarify the support to avoid looking in closed issues to find out?

**Comment by acabarbaye** [comment]
> 
> 
>     1. Is it really a definitve answer ?
> 
>     2. Could the readme clarify the support to avoid looking in closed issues to find out?

It would indeed be great to highlight in the ReadMe which version of OpenAPI is supported
