### ISSUE TITLE
Issues with deserializing breaking changes output

### ISSUE THREAD

**Issue by dsgouda** [Azure/openapi-diff#150]
As seen [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=37005), the breaking changes tool's output is not being successfully deserialized into a json

**Comment by praries880** [comment]
Same issue with this PR : https://github.com/Azure/azure-rest-api-specs/pull/6086.
Error : https://dev.azure.com/azure-sdk/public/_build/results?buildId=37808&view=logs&jobId=08b5038d-1e84-5877-88da-859df8312b69&taskId=c1978ecd-fc8a-5291-6d7a-7dd459d8b50f&lineStart=45&lineEnd=45&colStart=1&colEnd=21
