### ISSUE TITLE
Adding a type that was previously missing is breaking

### ISSUE THREAD

**Issue by johnthcall** [Azure/openapi-diff#167]
We had complaints from a user that our swagger was missing a type field. When we tried to add it the breaking changes trigger because the types differ. I don't know for sure if it is a real breaking change but will raise a PR in case it is a false positive.

id: '1026',
    code: 'TypeChanged',
    message: "The new version has a different type 'object' than the previous one ''.",
 Azure/azure-rest-api-specs#9215

**Comment by ruowan** [comment]
Thanks for the feedback. It is actually breaking change not false positive. Schema without type means all types are allowed. When you add type object, you constrain the type to object as a result, the property can't receive any other types.

**Comment by johnthcall** [comment]
Thanks for the explanation, it was a little unclear from the error messages we received.
