### ISSUE TITLE
Why is AddedPath considered a breaking change?

### ISSUE THREAD

**Issue by ctaggart** [Azure/openapi-diff#181]
Why is [1038 - AddedPath](https://github.com/Azure/openapi-diff/blob/master/docs/rules/1038.md) considered a breaking change? It is adding a path that did not exist before.

You can see it listed as a breaking change in https://github.com/Azure/azure-rest-api-specs-pr/pull/2408:
![image](https://user-images.githubusercontent.com/80104/100015427-cd6bd680-2d8c-11eb-87f6-b07330a7bcb4.png)

**Comment by jianyexi** [comment]
It's Azure new breaking change policy , adding path requires new API version
