### ISSUE TITLE
Runtime exception in breaking changes check...

### ISSUE THREAD

**Issue by subbartt** [Azure/openapi-diff#199]
Here is the PR request,

https://github.com/Azure/azure-rest-api-specs-pr/pull/3765

Runtime Exception

new":"https://github.com/Azure/azure-rest-api-specs-pr/blob/28ce553ccee04b7dd38b03adcd8db4c155800896/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2020-10-01-preview/connectedvmware.json",
"old":"https://github.com/Azure/azure-rest-api-specs-pr/blob/master/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2020-10-01-preview/connectedvmware.json",
"details":"File "/home/vsts/work/1/c93b354fd9c14905bb574a8834c4d69b/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2020-10-01-preview/connectedvmware.json" not found.

**Comment by jianyexi** [comment]
fixed , not caused by this tool, but the CI scripts
