### ISSUE TITLE
Tool causes "Breaking Change" phase to fail despite saying there are no breaking changes

### ISSUE THREAD

**Issue by tjprescott** [Azure/openapi-diff#212]
A team is attempting to remove a deprecated Swagger, which they have approval to do. However, the breaking change tool is failing and blocking us from merging the change:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1019104&view=logs&j=98f87804-8e1f-5655-af02-e80aefa7aa97&t=b99d49a6-f8c0-5971-07b4-95fc4d277e76

In the logs for the failure, it says:
`title: 'No potential breaking changes'`

Yet this exits with an error code 1 and fails the build.

**Comment by jianyexi** [comment]
This is a pipeline issue no the tool's issue, already fixed
