### ISSUE TITLE
Support OpenAPI3

### ISSUE THREAD

**Issue by BlitzkriegSoftware** [Azure/openapi-diff#219]
ASP.NET 3.1 LTS and higher produce OpenAPI3 as in this snippet:

```json
{
  "openapi": "3.0.1",
  ...
}
```

Produces this error
```text
FATAL: Error: File 'file:///....json' is not a valid OpenAPI 2.0 definition (expected 'swagger: 2.0')
```

It would be good to support OpenAPI3. See spec: https://swagger.io/specification/

**Comment by acabarbaye** [comment]
#148

**Comment by BlitzkriegSoftware** [comment]
try https://github.com/Tufin/oasdiff
