### ISSUE TITLE
Lint rule for adding new consumers

### ISSUE THREAD

**Issue by tadelesh** [Azure/openapi-diff#236]
From Jeffrey [suggested](https://github.com/Azure/autorest.go/issues/858), we need to add a lint rule for the situation: NEW response Content-Types always be added after OLD content types in the swagger.
This could be result in breaking changes for SDK to generate multi operations for each content type and make one of the content type as default. If we could not get previous version info, we can only relay on the sequence user provided. So, it will be an easier way to limit user only add new consumer after the existed one.

**Comment by jianyexi** [comment]
@tadelesh  if it's lint rule , please file issue via https://aka.ms/lintrulecandidate

**Comment by tadelesh** [comment]
Migrate to https://github.com/Azure/azure-openapi-validator/issues/371.
