### ISSUE TITLE
[Rule] breaking changes, when `x-ms-enum` change

### ISSUE THREAD

**Issue by tadelesh** [Azure/openapi-diff#242]
Several changes with `x-ms-enum` will cause breaking changes:
1. Add `x-ms-enum` in existed enum with different name with auto-generated one
2. Add `x-ms-enum` in existed enum with `modelAsString`
3. Change `x-ms-enum` `modelAsString`
4. Change `x-ms-enum` name

Related issue: https://github.com/Azure/azure-sdk-tools/issues/4073

**Comment by jianyexi** [comment]
@mikekistler could you help confirm this rule ?

**Comment by mikekistler** [comment]
I think all of the above will result in breaking changes in the generated SDKs:

1. will change the name of the enum
2. will change the enum type (in some SDKs) if `modelAsString` is set to "true"
3. will change the enum type (in some SDKs) 
4. will change the name of the enum

So all should be flagged as breaking.

**Comment by jianyexi** [comment]
I think the enum name change or type change are already covered, only need to check the 'name' and 'modelAsString' change for the x-ms-enum
