### ISSUE TITLE
[Rule 1048] Missing rule for x-ms-enum, AddedXmsEnum

### ISSUE THREAD

**Issue by RickWinter** [Azure/openapi-diff#252]
The tool references rule 1048 which does not exist.
https://github.com/Azure/openapi-diff/tree/master/docs/rules/1048.md

**Comment by jianyexi** [comment]
Thanks for feedback, it's actually in https://github.com/Azure/openapi-diff/tree/main/docs/rules/1048.md, will fix the pipeline issue
