### ISSUE TITLE
Address all failures in azure-rest-api-specs

### ISSUE THREAD

**Issue by mikeharder** [Azure/openapi-diff#294]
Part of [[Breaking Change] Runtime exceptions aggregate](https://github.com/Azure/azure-sdk-tools/issues/6169)

Known failures in azure-rest-api-specs:

- [x] Property `x-ms-enum.name` should be optional (#302)
- [ ] No enum match for "final-state-via:operation-location" (#310)
- [ ] Data does not match any schemas from 'oneOf'
  - https://github.com/Azure/azure-sdk-tools/issues/6998

### Handwritten Swagger
* https://github.com/Azure/azure-sdk-tools/issues/7278

### TypeSpec
* https://github.com/Azure/azure-rest-api-specs/pull/28080/checks?check_run_id=22418055934
   * Prioritize first since spec author is waiting
* https://github.com/Azure/azure-rest-api-specs/pull/25168/checks?check_run_id=22192854520

**Comment by konrad-jamrozik** [comment]
Another reason to get this in:
- https://github.com/Azure/azure-sdk-tools/issues/7833

**Comment by konrad-jamrozik** [comment]
@mikeharder here is a hint of how output format may change:

https://dev.azure.com/devdiv/DevDiv/_git/openapi-swaggerkpi/pullRequest/526141#1708025975
