### ISSUE TITLE
Adding "x-ms-long-running-operation": true is a breaking change

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/openapi-diff#93]
Per a discussion I had with @amarzavery and @lmazuel if an operation is changed to be long-running it constitutes a breaking change and the validator should mark it as such (presumably the inverse is also true).

**Comment by lmazuel** [comment]
Thanks @jhendrixMSFT ! I confirm at least for Python this is breaking both ways (i.e. true to false and false to true)

**Comment by jianyexi** [comment]
Added https://github.com/Azure/openapi-diff/blob/main/docs/rules/1044.md
